### ISSUE TITLE
LDAP 增加 filter ，只允许指定的用户才能登录

### ISSUE THREAD

**Issue by hale177** [opsre/WatchAlert#174]
```
Ldap:
  enabled: false
  # LDAP 服务地址
  address: "192.168.1.100:399"
  # 基础 DN
  baseDN: "dc=test,dc=com"
  # admin DN
  adminUser: "cn=admin,dc=test,dc=com"
  # admin 密码
  adminPass: "test123."
  # 用户 DN
  userDN: "ou=people,dc=test,dc=com"
  # 用户 DN 前缀
  userPrefix: "uid"
  # 默认用户角色
  defaultUserRole: "ur-cq7nkj1d6gviooaigqi0"
  # 定时任务，用于同步 LDAP 用户到W8T
  cronjob: "*/1 * * * *"
```

默认配置  ou=people 下所有用户都能登录，不太合理，建议增加 filter 过滤，
类似下面这样，过滤了只有 jms 组内的用户才能登录 。

![Image](https://github.com/user-attachments/assets/00a2e5e9-7d6f-433e-9648-bd4be48dad55)
